branch-defaults:
  aws:
    environment: blocklyExportTest-env
  master:
    environment: blocklyExportTest-env
deploy:
  artifact: deployments/web.zip
global:
  application_name: blockly_export_test
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
